baseURL: https://analystsuncertaintytoolkit.github.io/uncertainty_toolkit_govuk/
languageCode: en-gb
title: Uncertainty Toolkit for Analysts in Government
theme: govukhugo
publishDir: docs
canonifyurls: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  govuk: false
  logotext: UTAG
  product: Uncertainty Toolkit for Analysts in Government
  phase: beta
  feedbackurl: /contact/
  accessibility: Accessibility/_index.md
  contact: Contact/_index.md
